name: "Learn Run CI"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13' ]
    steps:
    - uses: actions/checkout@v4
    - name: Install uv and set up Python
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: uv sync --frozen --all-extras
    - name: Run tests
      run: uv run pytest
    - name: Check code linting
      run: uv run ruff check .
    - name: Check code formatting
      run: uv run ruff format --check .