name: "Learn Deploy Docs to GitHub Pages"

on:
  push:
    branches:
    - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv and set up Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: uv sync --group docs
      - name: Build MkDocs
        run: uv run mkdocs build --strict

      - name: Upload pages artifacts
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
