name: "Release"

on:
  push:
    branches: [ main ]

jobs:
  release:
    name: "Release Job"
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0 # Ensure full history is fetched for versioning
        - name: Install uv and set up Python
          uses: astral-sh/setup-uv@v6
          with:
            python-version: '3.13'

        - name: Install dependencies
          run: uv sync --frozen --all-extras

        - name: Run Semantic Release
          env:
            GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          run: uv run semantic-release version